- .github/workflows/build.yaml
- doc/changes/changes_0.1.0.md
- exasol_transformers_extension/udfs/bucketfs_operations.py
- exasol_transformers_extension/udfs/sequence_classification_single_text_udf.py
- poetry.lock
- tests/fixtures/model_fixture.py
- tests/integration_tests/with_db/test_model_downloader_udf_script.py
- tests/integration_tests/with_db/test_sequence_classification_single_text_script.py
- tests/integration_tests/without_db/test_sequence_classification_single_text_udf.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/multiple_model_multiple_batch_complete.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/multiple_model_multiple_batch_incomplete.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/multiple_model_multiple_batch_multiple_models_per_batch.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/multiple_model_single_batch_complete.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/multiple_model_single_batch_incomplete.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/single_model_multiple_batch_complete.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/single_model_multiple_batch_incomplete.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/single_model_single_batch_complete.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/single_model_single_batch_incomplete.py
- tests/unit_tests/udfs/test_sequence_classification_single_text.py
> #12: Update method for generating bucket udf path

- doc/changes/changes_0.1.0.md
- exasol_transformers_extension/deployment/constants.py
- exasol_transformers_extension/resources/templates/sequence_classification_text_pair_udf.jinja.sql
- exasol_transformers_extension/udfs/sequence_classification_text_pair_udf.py
- exasol_transformers_extension/udfs/sequence_classification_text_pair_udf_call.py
- tests/integration_tests/with_db/test_sequence_classification_text_pair_script.py
- tests/integration_tests/without_db/test_sequence_classification_single_text_udf.py
- tests/integration_tests/without_db/test_sequence_classification_text_pair_udf.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/mock_sequence_classification_factory.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/mock_sequence_tokenizer.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/multiple_model_multiple_batch_complete.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/multiple_model_multiple_batch_incomplete.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/multiple_model_multiple_batch_multiple_models_per_batch.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/multiple_model_single_batch_complete.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/multiple_model_single_batch_incomplete.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/single_model_multiple_batch_complete.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/single_model_multiple_batch_incomplete.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/single_model_single_batch_complete.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/single_model_single_batch_incomplete.py
- tests/unit_tests/udfs/test_sequence_classification_text_pair.py
> #14: Created squence classification text pair udf

- doc/changes/changes_0.1.0.md
- exasol_transformers_extension/udfs/models/filling_mask_udf.py
- exasol_transformers_extension/udfs/models/question_answering_udf.py
- exasol_transformers_extension/udfs/models/text_generation_udf.py
- exasol_transformers_extension/udfs/models/token_classification_udf.py
- exasol_transformers_extension/udfs/models/translation_udf.py
- tests/integration_tests/without_db/udfs/test_sequence_classification_single_text_udf.py
- tests/integration_tests/without_db/udfs/test_sequence_classification_text_pair_udf.py
- tests/integration_tests/without_db/udfs/test_translation_udf.py
- tests/unit_tests/udf_wrapper_params/filling_mask/mock_filling_mask.py
> #35: Setup filling mask pipeline once

- exasol_transformers_extension/udfs/models/sequence_classification_single_text_udf.py
- exasol_transformers_extension/udfs/models/sequence_classification_text_pair_udf.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/mock_sequence_classification_factory.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/mock_sequence_tokenizer.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/multiple_bfsconn_single_subdir_single_model_multiple_batch.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/multiple_bfsconn_single_subdir_single_model_single_batch.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/multiple_model_multiple_batch_complete.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/multiple_model_multiple_batch_incomplete.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/multiple_model_multiple_batch_multiple_models_per_batch.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/multiple_model_single_batch_complete.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/multiple_model_single_batch_incomplete.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/single_bfsconn_multiple_subdir_single_model_multiple_batch.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/single_bfsconn_multiple_subdir_single_model_single_batch.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/single_model_multiple_batch_complete.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/single_model_multiple_batch_incomplete.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/single_model_single_batch_complete.py
- tests/unit_tests/udf_wrapper_params/sequence_classification/single_model_single_batch_incomplete.py
> #20: Used Pipeline API in text classifications

- README.md
- doc/changes/changes_0.1.0.md
- doc/user_guide/user_guide.md
- setup.py
> #44: Added User Guide

- doc/changes/changes_0.1.0.md
> #48: Prepared the initial release

- .github/workflows/release_droid_upload_github_release_assets.yml
- doc/changes/changes_0.1.0.md
> #50: Fixed release_droid configuration

- doc/changes/changes_0.1.0.md
- poetry.lock
- pyproject.toml
> #54: Updated udf-mock-import

- .github/workflows/release_droid_upload_github_release_assets.yml
- doc/changes/changes_0.1.0.md
> #52: Added GH actions that free disk space

- .github/workflows/release_droid_upload_github_release_assets.yml
- doc/changes/changes_0.1.0.md
- doc/user_guide/user_guide.md
> #56: Split SLC into parts

- doc/changes/changelog.md
- doc/changes/changes_0.2.0.md
- doc/user_guide/user_guide.md
> #60: Updated the user guide

- doc/changes/changelog.md
- doc/changes/changes_0.3.0.md
- poetry.lock
- pyproject.toml
- setup.py
> #76: Updated torch version to 1.11.0

- doc/changes/changes_0.4.0.md
- doc/user_guide/user_guide.md
- exasol_transformers_extension/resources/templates/model_downloader_udf.jinja.sql
- exasol_transformers_extension/udfs/models/model_downloader_udf.py
- tests/integration_tests/with_db/udfs/test_model_downloader_udf_script.py
- tests/integration_tests/without_db/test_upload_model.py
- tests/integration_tests/without_db/udfs/test_download_pretrained_model.py
- tests/integration_tests/without_db/udfs/test_model_downloader_udf.py
- tests/unit_tests/udfs/test_model_downloader_udf.py
- tests/utils/parameters.py
> #72:  Added user token to download model from private repos

- doc/changes/changes_0.4.0.md
- doc/user_guide/user_guide.md
> #87: Updated user guide for added error message column

- doc/changes/changelog.md
- doc/changes/changes_0.5.0.md
- error_code_config.yml
> #86: Fixed error code config file

- README.md
- doc/changes/changes_0.5.0.md
- doc/developer_guide/developer_guide.md
- exasol_transformers_extension/udfs/models/base_model_udf.py
- setup.py
> #93: Added the Developer Guide

- exasol_transformers_extension/deployment/language_container.py
- language_container/exasol_transformers_extension_container/flavor_base/build_steps.py
- language_container/exasol_transformers_extension_container/flavor_base/dependencies/Dockerfile
- language_container/exasol_transformers_extension_container/flavor_base/release/Dockerfile
> #110: Splitted SLC into dependency and release build step

- tests/integration_tests/with_db/deployment/test_language_container_deployer_cli.py
> #84: Reactivated test after move to AWS

- doc/changes/changes_0.5.0.md
- tests/integration_tests/without_db/udfs/matcher.py
- tests/integration_tests/without_db/udfs/test_filling_mask_udf.py
- tests/integration_tests/without_db/udfs/test_question_answering_udf.py
- tests/integration_tests/without_db/udfs/test_sequence_classification_single_text_udf.py
- tests/integration_tests/without_db/udfs/test_sequence_classification_text_pair_udf.py
- tests/integration_tests/without_db/udfs/test_text_generation_udf.py
- tests/integration_tests/without_db/udfs/test_token_classification_udf.py
- tests/integration_tests/without_db/udfs/test_translation_udf.py
- tests/integration_tests/without_db/udfs/test_zero_shot_text_classification_udf.py
> #121: Use matchers for asserts in without db integration tests

- doc/changes/changes_0.5.0.md
- doc/user_guide/user_guide.md
- exasol_transformers_extension/deployment/deployment_utils.py
- exasol_transformers_extension/deployment/language_container_deployer.py
- exasol_transformers_extension/deployment/language_container_deployer_cli.py
- exasol_transformers_extension/deployment/scripts_deployer.py
- exasol_transformers_extension/deployment/scripts_deployer_cli.py
- exasol_transformers_extension/upload_model.py
- githooks/pre-commit
- tests/integration_tests/with_db/deployment/test_language_container_deployer_cli.py
- tests/integration_tests/with_db/deployment/test_scripts_deployer.py
- tests/integration_tests/with_db/deployment/test_scripts_deployer_cli.py
- tests/integration_tests/with_db/test_upload_model.py
> #103: Added option to toggle TLS cert validation

- .github/workflows/release_droid_upload_github_release_assets.yml
- doc/changes/changes_0.5.0.md
> Fix release workflow

- doc/changes/changelog.md
- doc/changes/changes_0.6.0.md
- poetry.lock
- pyproject.toml
> #136: Configobj removed and prepare release

- doc/changes/changelog.md
- doc/changes/changes_0.8.0.md
- poetry.lock
- pyproject.toml
> Updated paramiko

- doc/changes/changes_0.8.0.md
- poetry.lock
- pyproject.toml
> Updated transformers

- doc/changes/changes_0.9.1.md
Fixes missed version number update, no issue
> Prepare release 0.9.1

- doc/changes/changelog.md
- doc/changes/changes_0.9.2.md
- poetry.lock
- pyproject.toml
* [x ] Is the title of the corresponding issue correct?
*
> Updated exasol-bucketfs dependency, removed typeguard [CodeBuild]

- .github/workflows/release_droid_upload_github_release_assets.yml
- doc/changes/changes_0.10.0.md
> Release to PyPi

- doc/changes/changes_0.10.0.md
> Release to PyPi second attempt

- doc/changes/changes_0.10.1.md
- poetry.lock
> Updated cryptography to  42.0.5

- doc/changes/changes_0.10.1.md
- vagrant/Vagrantfile
- vagrant/provisioning/dns.sh
- vagrant/provisioning/install.sh
- vagrant/provisioning/install_poetry.sh
- vagrant/provisioning/resize-disk.sh
> #205: Added vagrant setup

- doc/user_guide/user_guide.md
- exasol_transformers_extension/deployment/te_language_container_deployer.py
- poetry.lock
- tests/unit_tests/deployment/test_language_container_deployer.py
> #234 Added wait-for-completion parameter to the SLC deployer

- doc/changes/changes_2.0.0.md
- poetry.lock
- pyproject.toml
> #238: Fixed reference to python-extension-common

- .github/actions/prepare_poetry_env/action.yml
- .github/pull_request_template.md
- .github/workflows/build.yaml
- .github/workflows/release_droid_upload_github_release_assets.yml
- buildspec.yml
- doc/changes/changes_2.0.0.md
- doc/dependencies.md
- doc/developer_guide/developer_guide.md
- language_container/exasol_transformers_extension_container/flavor_base/dependencies/Dockerfile
- language_container/exasol_transformers_extension_container/flavor_base/release/Dockerfile
- poetry.lock
- pyproject.toml
- vagrant/provisioning/install.sh
- vagrant/provisioning/install_poetry.sh
>  Python 3.10 update

- doc/changes/changes_2.0.0.md
- doc/user_guide/user_guide.md
> #247 SaaS deployment documentation

- .github/workflows/build.yaml
- buildspec.yml
- doc/changes/changes_2.0.0.md
- exasol_transformers_extension/deployment/scripts_deployer.py
- exasol_transformers_extension/upload_model.py
- tests/conftest.py
- tests/fixtures/bucketfs_fixture.py
- tests/fixtures/database_connection_fixture.py
- tests/fixtures/language_container_fixture.py
- tests/fixtures/model_fixture.py
- tests/fixtures/script_deployment_fixture.py
- tests/fixtures/setup_database_fixture.py
- tests/integration_tests/with_db/deployment/test_scripts_deployer.py
- tests/integration_tests/with_db/deployment/test_scripts_deployer_cli.py
- tests/integration_tests/with_db/test_upload_model.py
- tests/integration_tests/with_db/udfs/test_filling_mask_script.py
- tests/integration_tests/with_db/udfs/test_model_downloader_udf_script.py
- tests/integration_tests/with_db/udfs/test_prediction_with_downloader_udf.py
- tests/integration_tests/with_db/udfs/test_question_answering_script.py
- tests/integration_tests/with_db/udfs/test_sequence_classification_single_text_script.py
- tests/integration_tests/with_db/udfs/test_sequence_classification_text_pair_script.py
- tests/integration_tests/with_db/udfs/test_text_generation_script.py
- tests/integration_tests/with_db/udfs/test_token_classification_script.py
- tests/integration_tests/with_db/udfs/test_translation_script.py
- tests/integration_tests/with_db/udfs/test_zero_shot_text_classification_script.py
- tests/integration_tests/with_db/utils/test_huggingface_hub_bucketfs_model_transfer_sp.py
- tests/utils/db_queries.py
- tests/utils/parameters.py
> #244 Running most of the tests in SaaS [CodeBuild]

- poetry.lock
> Relock 16.12.24

- doc/changes/changelog.md
- doc/changes/changes_2.2.0.md
> fixed copy paste error and release date

- doc/changes/changelog.md
- doc/changes/changes_2.2.1.md
- exasol_transformers_extension/utils/huggingface_hub_bucketfs_model_transfer_sp.py
- exasol_transformers_extension/utils/model_factory_protocol.py
- pyproject.toml
- tests/fixtures/model_fixture_utils.py
- tests/integration_tests/with_db/utils/test_huggingface_hub_bucketfs_model_transfer_sp.py
- tests/integration_tests/without_db/udfs/test_model_downloader_udf.py
- tests/integration_tests/without_db/utils/test_load_local_model.py
- tests/unit_tests/utils/test_huggingface_hub_bucketfs_model_transfer_sp.py
> #287: Used the correct AutoModel class in tests.fixtures.model_fixture_utils.download_model_to_path
